- name: Linux OS Mandotory Patches
  hosts: all
  tasks:
    - name: Fetching all available packages
      yum:
        list: package_name
        register: fetched_packages_names
        
    - debug: List all avaialble upgradeable packages
        var=fetched_packages_names
