- name: Linux OS Mandotory Patches
  hosts: all
  tasks:
    - name: Fetching all available packages
      yum:
        list: updates
        register: available_updates
        when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
        
    - debug: List all avaialble upgradeable packages
      msg: "{{ yumoutput.results | map(attribute='name') | list }}
