- name: Linux OS Mandotory Patches
  hosts: all
  gather_facts: true
  tasks:
    - name: get installed packages
      yum:
        list: installed
      register: packages_installed
    - debug: var=packages_installed

    - name: get available packages updates
      yum:
        list: updates
        update_cache: true
      register: packages_update
    - debug: var=packages_update
