- name: Linux OS Mandotory Patches
  hosts: all
  tasks:
    - name: Fetching all available packages
      yum:
        list: package_name

    - name:
      debug: List all avaialble upgradeable packages
        var: package_name
