- name: Linux OS Mandotory Patches
  hosts: all
  tasks:
    - name: RHEL Security Patches
      shell:
        cmd: yum check-update
      debug:
        msg: "System Logged in successfully to {{ ansible_distribution }}"
