- name: Linux OS Mandotory Patches
  hosts: all
  tasks:
    - name: get package version
      yum:
        list: package_name
      register: package_name_version

    - name: set package version
      set_fact:
        package_name_version: "{{ package_name_version.results|selectattr('yumstate','equalto','installed')|map(attribute='version')|list|first }}"
